# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# 한국어 (기본 언어)
ko:
  languageCode: ko-kr
  languageName: 한국어
  weight: 2
  title: "마음의 홈페이지"
  params:
    description: "전북대학교 컴퓨터인공지능학부 학생 마음의 포트폴리오 및 학습 기록"
  contentDir: content/ko

# English (두 번째 언어)
en:
  languageCode: en-us
  languageName: English
  weight: 1
  title: "MaEum's Homepage"
  params:
    description: "Portfolio of MaEum, Computer Science and AI student at JBNU"
  contentDir: content/en