# English menu
main:
  - name: Bio
    url: /
    weight: 10
  - name: Talks
    url: /events/
    weight: 12
  - name: Experience
    url: experience/
    weight: 20
  - name: Projects
    url: projects/
    weight: 30
  - name: Courses
    url: courses/
    weight: 40