# Korean menu
main:
  - name: 소개
    url: /
    weight: 10
  - name: 강연
    url: /events/
    weight: 12
  - name: 경험
    url: experience/
    weight: 20
  - name: 프로젝트
    url: projects/
    weight: 30
  - name: 이수 과목
    url: courses/
    weight: 40